baseURL = "https://luckyuhuns.com/"
disableLanguages = ["Fr"]
disqusShortname = "marketing-ot"
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Lucky Uhuns"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Lucky Uhuns](https://luckyuhuns.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Lucky Uhuns](https://luckyuhuns.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "https://www.luckyuhuns.com/blog/"
name = "Blog"
weight = ""
[[menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[menu.main]]
URL = "project"
name = "Project"
weight = "2"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "service"
name = "Service"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[params]
author = "Lucky Uhuns"
contact_form_action = "uhunslucky@gmail.com"
description = ""
email = "uhunslucky@gmail.com"
google_analitycs_id = "UA-115105183-3"
location = "Corporation drive, dolphin estate, ikoyi, Lagos."
logo = "/images/luckyuhuns_logo.png"
mobile = "+2348169627988"
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "https://www.linkedin.com/in/lucky-uhunmwangho-0524a4110"
[[params.social]]
icon = "ion-social-youtube-outline"
link = "#"
[[params.social]]
icon = "ion-social-instagram-outline"
link = "https://www.instagram.com/luckyuhuns"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com/luckyuhuns"
